---
title: "Data Management Plan Training"
knitr:
  opts_knit: 
    message: false
    warning: false
    echo: false
---

## Course description

This course is offered by the 3mE Graduate School to support PhD students at the 3mE faculty with the Research Data Mangement [policy](https://d2k0ddhflgrk1i.cloudfront.net/Library/Themaportalen/RDM/Beleid/2020_3mE_Research_Data_Management_Policy.pdf) requirements. The course consists of lectures with recommendations for data storage, project organisation, and data sharing and archiving. There will also be a practical component where students will get hands-on experience developing a Data Management Plan (DMP) using the [DMPonline](https://dmponline.tudelft.nl) platform.

## Schedule

### Part 1

TBD

### Part 3

```{r}
#| echo: false
#| message: false
library(dplyr)
library(readr)
library(lubridate)
schedule <- read_csv("2022-2023_training-sessions.csv")

schedule %>%
    filter(Date > Sys.Date(),
        Session == "Part 3") %>%
    select(!Session) %>%
    knitr::kable()
```

## Training outcomes

At the end of the course, you should be familiar with:

- The importance of proper data...
    + management
    + storage
    + documentation
- Developing your own DMP
- Personal data considerations

## Important info

The course will take 5.5 - 7 h (depending if your DMP includes collection of personal data)
divided into three parts over 6 – 9 months.

You will receive 1 GS for completing the training.

Certificates will be provided after the sessions, and can be uploaded to [DMA](dma.tudelft.nl) (You can choose any of the three categories in DMA).

If you need to submit your PhD agreement before following one of these trainings, under the section Other Arrangements – Data Management Plan, depending on the training you will follow, you can indicate one of the following:

1. Data Management Plan Training for 3mE PhD students
    - You are going to follow Data Management Plan Training for 3mE PhD students delivered by the faculty data steward within the first year of the PhD.
    - During this training, you will create a DMP in DMPonline and consult the faculty data steward.
    - After the training, you will discuss your DMP with your PhD supervisor(s).  
    - You will include your DMP in the Go/No Go Decision. 
2. Research Data Management 101
    - You are going to follow Research Data Management 101 delivered by the TU Delft Library within the first year of the PhD. 
    - During this training, you will create a DMP in DMPonline and consult the trainers, and the faculty data steward if needed.
    - After the training, you will discuss your DMP with your PhD supervisor(s).  
    - You will include your DMP in the Go/No Go Decision. 

It is the responsibility of the PhD supervisor(s) to approve the DMP, not the Data Steward. A guide for this can be found [here](https://d1rkab7tlqy5f1.cloudfront.net/Library/Themaportalen/RDM/5%20Things%20to%20check%20when%20looking%20at%20Data%20Management%20Plans%20%28DMPs%29%20-%20guidance%20for%20supervisors%20-%20FINAL%20VERSION%20%281%29.pdf).

## 3mE data management policy summary {#policy-summary}

All PhD students who started from Jan 2020:

- develop a written DMP for managing research outputs within the first 12 months.
- attend relevant training in data management
- Ensure that all data and code underlying completed PhD theses are appropriately documented and accessible for at least 10 years from the end of the research project, in accordance with the [FAIR principles](https://www.go-fair.org/fair-principles/), unless there are valid reasons which make research data unsuitable for sharing

## Important links

- [DMPonline (TU Delft)](https://dmponline.tudelft.nl)
- [Brightspace module for Part 3](https://brightspace.tudelft.nl/d2l/le/content/471218)
- [3mE faculty policy for data management](https://d2k0ddhflgrk1i.cloudfront.net/Library/Themaportalen/RDM/Beleid/2020_3mE_Research_Data_Management_Policy.pdf)